export enum Speciality {
  CARDIOLOGY = 1,
  DERMATOLOGY,
  GYNECOLOGY,
  ORTHOPEDICS,
  ANESTHESIOLOGY,
  PEDIATRICS,
  OPHTHALMOLOGY,
  PSYCHIATRY,
  UROLOGY,
  ONCOLOGY,
  ENDOCRINOLOGY,
  NEUROLOGY,
  HEMATOLOGY,
  PLASTIC_SURGEON,
  GENERAL_SURGEON
}
